# Generated by Django 4.0.5 on 2022-08-22 14:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libralian', '0004_remove_fines_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fines',
            name='actual_return_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 14, 35, 54, 603767, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fines',
            name='date_taken',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 14, 35, 54, 603767, tzinfo=utc), editable=False),
        ),
    ]
