# Generated by Django 4.0.5 on 2022-08-22 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libralian', '0007_alter_fines_actual_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fines',
            name='actual_return_date',
            field=models.DateField(default=datetime.date(2022, 8, 26)),
        ),
        migrations.AlterField(
            model_name='fines',
            name='date_taken',
            field=models.DateField(default=datetime.date(2022, 8, 22), editable=False),
        ),
    ]
