# Generated by Django 4.0.5 on 2022-08-22 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libralian', '0009_returnedbook_takenbook_delete_fines'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedbook',
            name='fine',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnedbook',
            name='actual_return_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 23, 14, 51, 543521)),
        ),
        migrations.AlterField(
            model_name='returnedbook',
            name='date_taken',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 23, 14, 51, 543521)),
        ),
        migrations.AlterField(
            model_name='returnedbook',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 23, 14, 51, 543521)),
        ),
        migrations.AlterField(
            model_name='takenbook',
            name='date_taken',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 23, 14, 51, 452624)),
        ),
        migrations.AlterField(
            model_name='takenbook',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 23, 14, 51, 452624)),
        ),
    ]
