# Generated by Django 4.0.5 on 2022-08-23 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libralian', '0010_returnedbook_fine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedbook',
            name='actual_return_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 23, 23, 38, 34, 696828)),
        ),
        migrations.AlterField(
            model_name='returnedbook',
            name='date_taken',
            field=models.DateField(default=datetime.datetime(2022, 8, 23, 23, 38, 34, 696828)),
        ),
        migrations.AlterField(
            model_name='returnedbook',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 23, 23, 38, 34, 696828)),
        ),
        migrations.AlterField(
            model_name='takenbook',
            name='date_taken',
            field=models.DateField(default=datetime.datetime(2022, 8, 23, 23, 38, 34, 614887)),
        ),
        migrations.AlterField(
            model_name='takenbook',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 23, 23, 38, 34, 614887)),
        ),
    ]
