# Generated by Django 4.0.5 on 2022-08-23 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libralian', '0011_alter_returnedbook_actual_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedbook',
            name='actual_return_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 24, 0, 51, 7, 801998)),
        ),
        migrations.AlterField(
            model_name='returnedbook',
            name='date_taken',
            field=models.DateField(default=datetime.datetime(2022, 8, 24, 0, 51, 7, 801998)),
        ),
        migrations.AlterField(
            model_name='returnedbook',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 24, 0, 51, 7, 801998)),
        ),
        migrations.AlterField(
            model_name='takenbook',
            name='date_taken',
            field=models.DateField(default=datetime.datetime(2022, 8, 24, 0, 51, 7, 532026)),
        ),
        migrations.AlterField(
            model_name='takenbook',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 24, 0, 51, 7, 532026)),
        ),
    ]
