# Generated by Django 4.0.5 on 2022-08-02 07:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION1', '0007_remove_book_due_date_remove_book_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 7, 37, 35, 185798, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 7, 37, 35, 185798, tzinfo=utc)),
        ),
    ]
