# Generated by Django 4.0.5 on 2022-08-04 08:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION1', '0008_book_description_alter_book_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20, null=True)),
                ('bookcover', models.ImageField(upload_to='')),
                ('user_name', models.CharField(max_length=50)),
                ('student_id', models.IntegerField()),
                ('booking_start', models.DateTimeField(default=datetime.datetime(2022, 8, 4, 8, 31, 29, 106703, tzinfo=utc))),
                ('booking_end', models.DateTimeField(default=datetime.datetime(2022, 8, 4, 8, 31, 29, 106703, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('actual_return_date', models.DateField()),
                ('extra_days', models.IntegerField()),
                ('fine', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 8, 31, 29, 106703, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 8, 31, 29, 106703, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPLICATION1.student')),
            ],
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_date', models.DateField(blank=True, null=True, verbose_name='Date of book request')),
                ('book_id', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPLICATION1.student')),
            ],
        ),
    ]
