# Generated by Django 4.0.5 on 2022-08-04 08:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION1', '0009_bookedbook_fines_student_alter_book_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 8, 33, 1, 43050, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 8, 33, 1, 43050, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bookedbook',
            name='booking_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 8, 33, 1, 43050, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bookedbook',
            name='booking_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 8, 33, 1, 43050, tzinfo=utc)),
        ),
    ]
