# Generated by Django 4.0.5 on 2022-08-22 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION1', '0019_alter_book_created_alter_book_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedbook',
            name='booking_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 21, 49, 46, 50975)),
        ),
        migrations.AlterField(
            model_name='bookedbook',
            name='booking_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 21, 49, 46, 50975)),
        ),
    ]
