# Generated by Django 4.0.5 on 2022-08-22 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION1', '0020_alter_bookedbook_booking_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedbook',
            name='booking_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 21, 50, 57, 569302)),
        ),
        migrations.AlterField(
            model_name='bookedbook',
            name='booking_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 21, 50, 57, 569302)),
        ),
    ]
