# Generated by Django 4.0.5 on 2022-08-22 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION1', '0022_alter_book_created_alter_bookedbook_booking_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 22, 14, 13, 787675)),
        ),
        migrations.AlterField(
            model_name='bookedbook',
            name='booking_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 22, 14, 13, 787675)),
        ),
        migrations.AlterField(
            model_name='bookedbook',
            name='booking_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 22, 14, 13, 787675)),
        ),
    ]
