# Generated by Django 4.0.5 on 2022-08-23 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION1', '0024_alter_book_created_alter_bookedbook_booking_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created',
        ),
        migrations.RemoveField(
            model_name='book',
            name='modified',
        ),
        migrations.AlterField(
            model_name='bookedbook',
            name='booking_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 23, 38, 34, 761107)),
        ),
        migrations.AlterField(
            model_name='bookedbook',
            name='booking_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 23, 38, 34, 761107)),
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
