# Generated by Django 4.0.5 on 2022-08-23 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION1', '0025_remove_book_created_remove_book_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedbook',
            name='booking_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 0, 51, 7, 911988)),
        ),
        migrations.AlterField(
            model_name='bookedbook',
            name='booking_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 0, 51, 7, 911988)),
        ),
    ]
